### ISSUE TITLE
small tutorial on working with Angular HTTP

### ISSUE THREAD

**Issue by baeron** [xripcsu/rxjs-watcher#1]
Thanks for the tool. And you can write a small tutorial on working with Angular HTTP and display unsubscribe from the stream?

**Comment by xripcsu** [comment]
Hi, completion of observable should be visible as vertical line (like [here](https://github.com/xripcsu/rxjs-watcher#groups)), if you can not see it and you are sure that your stream really is unsubscribed, please let me know more.

You should be able use extension with Angular HttpClient like this
```ts 
this.http.get('url').pipe(
  watch('http request', 10)
).subscribe()
```
I hope it will help.
