### ISSUE TITLE
Any way to disable watch ?

### ISSUE THREAD

**Issue by iangregsondev** [xripcsu/rxjs-watcher#6]
Hi,

great extension and library!

It got me thinking, and its great while developing. Is there any way to disable it when I deploy to production?

Maybe calling into some kind of enable / disable or passing a boolean.

The Watch remains in the code but internally it does nothing.

Thanks in advance

**Comment by xripcsu** [comment]
Hi,

Thank you.
I published new version to npm. Now you can use function to disable watch globally like this 
```typescript
import {disableRxjsWatcher} from 'rxjs-watcher'
if(isProduction) {
  disableRxjsWatcher()
} 
```

**Comment by iangregsondev** [comment]
Great ! Thank you, I will check it out.

**Comment by JackCA** [comment]
Can we add documentation for this on the README?
