### ISSUE TITLE
Values produced using from and of operator overlapped with each other

### ISSUE THREAD

**Issue by ashwinmenkudle** [xripcsu/rxjs-watcher#8]
The panel does not have a way to select the values produced using from and of the operator.
Value points on line overlap with each other so values can not be analyzed on the right handle side panel.

![overlap](https://user-images.githubusercontent.com/5318013/79039056-3aff3400-7bfc-11ea-89b3-636e60690f50.JPG)

**Comment by ashwinmenkudle** [comment]
Created pull request for this issue
#7

**Comment by xripcsu** [comment]
fixed
